###
GET http://localhost:3000/api/user?page=1&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSJ9LCJpYXQiOjE3MDY2MzM0NTQsImV4cCI6MjEzODYzMzQ1NH0.TIit0A2PaMnxxy3iCpstjXZ_umGC25xSrWKvuIhqcvA

###
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "Jorge",
    "email": "test@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "admin"
}


###
GET http://localhost:3000/api/user/1

###
PUT http://localhost:3000/api/user/1
Content-Type: application/json

{
    "name": "Jorge Vivas"
}

###
DELETE  http://localhost:3000/api/user/2

###
POST http://localhost:3000/api/user/email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSJ9LCJpYXQiOjE3MDY0NDAwMjYsImV4cCI6MjEzODQ0MDAyNn0.TUjVPlt8r0UuZseeIO421CSz-rj_iHt8Adq5fBMraIc

{
    "email": "test@gmail.com"
}

###
PUT http://localhost:3000/api/user/3/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSJ9LCJpYXQiOjE3MDY0NDAwMjYsImV4cCI6MjEzODQ0MDAyNn0.TUjVPlt8r0UuZseeIO421CSz-rj_iHt8Adq5fBMraIc

{
    "role": "editor"
}

###
PUT http://localhost:3000/api/user/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJuYW1lIjoiSm9yZ2UiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIn0sImlhdCI6MTcwNjQ0MjcwNywiZXhwIjoyMTM4NDQyNzA3fQ.oHvdVGBCmfYNeWps_h8huBXbzSUoXKmjsVH2cd7YZo0

{
  "name": "Jorge Vivas"
}

####
POST http://localhost:3000/api/user/exist
Content-Type: application/json

{
    "email": "test@gmail.com"
}